from pytube import YouTube
from pytube import Playlist
from os import getcwd
from os import listdir
from os import path
from os import remove
from moviepy.audio.io.ffmpeg_audiowriter import ffmpeg_audiowrite
from moviepy.audio.io.AudioFileClip import AudioFileClip
from pathlib import Path  